language: python
python: 3.9

jobs:
  include:
    - python: '3.9'
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - coveralls
