sudo: false

language: python
python: 3.6

install:
  - pip install codecov

script:
  - coverage run tests.py

jobs:
  include:
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'

after_success:
  - codecov
